import { describe, expect, it, vi } from 'vitest';

vi.mock('@/lib/supabaseClient', () => ({ supabase: { auth: {} } }));

import { ApiError, api, emptyMySubmissions } from '../api';

/** Every endpoint method the app calls through `api`, captured before lib/api.ts was split by domain. */
const METHODS = [
  'acceptProjectJoinRequest',
  'addManualRosterStudent',
  'addProjectMember',
  'assignAdmin',
  'assignProductOwner',
  'assignProjectTA',
  'assignScrumMaster',
  'bulkInviteStudents',
  'cancelInvite',
  'cancelJoinRequest',
  'cancelTeamInvite',
  'checkEmail',
  'createAssignment',
  'createClass',
  'createClassProject',
  'createProject',
  'createProjectTsr',
  'createUser',
  'deleteAssignment',
  'deleteConversation',
  'deleteManualRosterEntry',
  'deleteProject',
  'demoteTA',
  'dismissJoinRequest',
  'getAssignmentTsrOverview',
  'getAssignments',
  'getClass',
  'getClassProjects',
  'getClassProjectsOverview',
  'getClassRoster',
  'getClassRosterTimeline',
  'getClassStudents',
  'getClassTAs',
  'getClassTaRoster',
  'getClassTurnInStats',
  'getClasses',
  'getClassesAttentionSummary',
  'getContacts',
  'getConversations',
  'getFeedbackOverview',
  'getFinalReviewDetail',
  'getFinalReviewSchedule',
  'getIncomingJoinRequests',
  'getInstitutions',
  'getMessages',
  'getMyAssignedTeams',
  'getMyAssignmentTsrs',
  'getMyEnrollmentRole',
  'getMyFeedback',
  'getMyInterestSubmission',
  'getMyInterests',
  'getMyJoinRequests',
  'getMySubmissions',
  'getMyTeamSchedule',
  'getNotifications',
  'getPendingTeamInvites',
  'getProject',
  'getProjectJoinRequests',
  'getProjectMembers',
  'getProjectPendingInvites',
  'getProjectTAs',
  'getProjectTsrs',
  'getProjects',
  'getStaffingAssignments',
  'getStaffingProjectRank',
  'getStaffingStudents',
  'getTAMeetingSchedule',
  'getTAReviewTargets',
  'getTeamAttendance',
  'inviteStudent',
  'joinClass',
  'leaveClass',
  'loginCheck',
  'markAllNotificationsRead',
  'markAllPresent',
  'markConversationRead',
  'markNotificationRead',
  'promoteToTA',
  'queueInvite',
  'rejectProjectJoinRequest',
  'releaseReviewTA',
  'removeAdmin',
  'removeProductOwner',
  'removeProjectMember',
  'removeScrumMaster',
  'removeStudentFromClass',
  'requestJoinProject',
  'saveFinalReviewNotes',
  'saveFinalReviewScores',
  'sendMessage',
  'setClassTA',
  'setFinalReviewTime',
  'setMeetingCadence',
  'setReviewTA',
  'setReviewWindow',
  'setReviewZoom',
  'staffingAssign',
  'staffingAutoAssign',
  'staffingUnassign',
  'submitFeedback',
  'submitInterestForm',
  'updateAssignment',
  'updateAssignmentTsr',
  'updateClassStatus',
  'updateProject',
  'updateProjectMeeting',
  'uploadClassRoster',
  'upsertAttendance',
];

describe('api facade', () => {
  it('exposes every endpoint method', () => {
    expect(Object.keys(api).sort()).toEqual(METHODS);
    for (const name of METHODS) {
      expect(typeof (api as Record<string, unknown>)[name]).toBe('function');
    }
  });

  it('re-exports the shared values and the error type', () => {
    expect(emptyMySubmissions()).toEqual({ tsrs: [], feedback_assignment_ids: [] });
    expect(new ApiError(404, 'Not found', 'Request failed')).toBeInstanceOf(Error);
  });
});
