import type { AssignProject, Student } from './assignTypes';

export const MOCK_PROJECTS: AssignProject[] = [
  {
    id: 'p1',
    name: 'Library Management System',
    sponsor: 'Tech Corp',
    popularity: 4.2,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p2',
    name: 'E-Commerce Platform',
    sponsor: 'Retail Solutions Inc',
    popularity: 4.8,
    seatsTaken: 0,
    totalSeats: 4,
  },
  {
    id: 'p3',
    name: 'Student Portal Redesign',
    sponsor: 'University IT',
    popularity: 3.5,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p4',
    name: 'Mobile Fitness Tracker',
    sponsor: 'HealthTech LLC',
    popularity: 4.6,
    seatsTaken: 0,
    totalSeats: 4,
  },
  {
    id: 'p5',
    name: 'Smart Campus Navigator',
    sponsor: 'CampusLabs',
    popularity: 4.0,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p6',
    name: 'Research Paper Recommender',
    sponsor: 'Academia AI',
    popularity: 3.8,
    seatsTaken: 0,
    totalSeats: 4,
  },
  {
    id: 'p7',
    name: 'Volunteer Matching App',
    sponsor: 'GiveBack Co',
    popularity: 4.3,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p8',
    name: 'Carbon Footprint Tracker',
    sponsor: 'GreenStart',
    popularity: 4.1,
    seatsTaken: 0,
    totalSeats: 4,
  },
  {
    id: 'p9',
    name: 'Peer Tutoring Platform',
    sponsor: 'EduBridge',
    popularity: 3.9,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p10',
    name: 'AR Museum Experience',
    sponsor: 'ARtistry Inc',
    popularity: 4.7,
    seatsTaken: 0,
    totalSeats: 4,
  },
  {
    id: 'p11',
    name: 'Local Events Aggregator',
    sponsor: 'CityPulse',
    popularity: 3.6,
    seatsTaken: 0,
    totalSeats: 5,
  },
  {
    id: 'p12',
    name: 'Accessibility Audit Tool',
    sponsor: 'InclusiveTech',
    popularity: 4.4,
    seatsTaken: 0,
    totalSeats: 4,
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Sarah Chen',
    email: 'schen@gatech.edu',
    interest: { forFocusedProject: 5, availableMatches: 3 },
    notes: 'Very proactive student with strong technical skills.',
    previousProjectName: 'Campus Food Delivery App',
    previousProjectId: 'p-prev-1',
    takingCS115C: true,
    preferences: [
      {
        projectId: 'p1',
        projectName: 'Library Management System',
        rating: 5,
        reason:
          'I have experience with database design and would love to work on a system that helps organize information.',
      },
      {
        projectId: 'p2',
        projectName: 'E-Commerce Platform',
        rating: 4,
        reason: 'Interested in building scalable backend systems.',
      },
    ],
  },
  {
    id: 's2',
    name: 'Michael Rodriguez',
    email: 'mrodriguez@gatech.edu',
    interest: { forFocusedProject: 3, availableMatches: 2 },
    notes: 'Strong team player, prefers frontend work.',
    previousProjectName: 'Event Booking Platform',
    takingCS115C: false,
    teammateIds: ['s3', 's4'],
    preferences: [
      {
        projectId: 'p3',
        projectName: 'Student Portal Redesign',
        rating: 5,
        reason: 'Love working on UI/UX and accessibility.',
      },
    ],
  },
  {
    id: 's3',
    name: 'Emily Johnson',
    email: 'ejohnson@gatech.edu',
    interest: { forFocusedProject: 4, availableMatches: 4 },
    takingCS115C: true,
    preferences: [],
  },
  {
    id: 's4',
    name: 'David Kim',
    email: 'dkim@gatech.edu',
    interest: { forFocusedProject: 4, availableMatches: 2 },
    takingCS115C: false,
    preferences: [],
  },
  {
    id: 's5',
    name: 'Jessica Williams',
    email: 'jwilliams@gatech.edu',
    interest: { forFocusedProject: 2, availableMatches: 2 },
    takingCS115C: true,
    preferences: [],
  },
  {
    id: 's6',
    name: 'Alex Thompson',
    email: 'athompson@gatech.edu',
    interest: { forFocusedProject: 3, availableMatches: 3 },
    takingCS115C: false,
    preferences: [],
  },
  {
    id: 's7',
    name: 'Priya Patel',
    email: 'ppatel@gatech.edu',
    interest: { forFocusedProject: 5, availableMatches: 4 },
    takingCS115C: true,
    preferences: [],
  },
];

export const INITIAL_UNASSIGNED_COUNT = 10;
